class ResponseCodes():
    LOGIN_RESPONSE_SUCCESS = 0
    LOGIN_RESPONSE_SERVERINITFAILED = 1
    LOGIN_RESPONSE_USER_NOT_FOUND = 2
    LOGIN_RESPONSE_INVALID_PASSWORD = 3
    LOGIN_RESPONSE_INVALID_PROFILE = 4
    LOGIN_RESPONSE_UNIQUE_NICK_EXPIRED = 5
    LOGIN_RESPONSE_DB_ERROR = 6
    LOGIN_RESPONSE_SERVER_ERROR = 7